* Overview
The perception of intonation can be simulated by low-pass filtering a speech signal at, say 200Hz or 500Hz, in order to create a somewhat muffled version of a recoding, which preserves the pitch of the original signal.
This program to process a speech signal x(i) using the 5th order low-pass Butterworth filter and to play the processed signal y(i).
The 5th order Butterworth filter can be expressed as

y(i) = b_{0} x(i) + b_{1} x(i -1) + ... + b_{5} x(i - 5) - a{1} y(i - 1) - a_{2}y(i - 2) - ... - a_{5}y(i - 5)

where the filter coefficients ܾ b_{0}, b_{1}, ... , b_{5} and a_{1}, a_{2}, ... , a_{5} can be found in the Appendix according to the required cut-off frequency f_{c} and the sampling frequency f_{s} of the speech signal.
* Feature
1. The program be named as “lpplay” and read the cut-off frequency f_{c} value, either 200 Hz or 500 Hz, from the command lines and take one WAV audio file as the input audio x(i). For instance, the command line may look like this
$lpplay f_{c} file.wav --- where f_{c} is either 200 or 500 and other values are invalid.

2. The program can display the usage of the program and exists when it is invoked as follows
$ lpplay –help

3. The program can support 16 bit mono WAV files whose sampling frequencies are either 22050Hz or 44100Hz. For unsupported WAV files, the program will display a message saying that the WAV format is not supported and display the following information on the file.wav and then exist.
+ Number of channels
+ Number of bits per sampl
+ Sampling frequency
+ Duration in seconds

4. Users can able to switch the audio playing through the following keys:
+ Key ‘r’ or R’: rewind to the beginning of the audio and play
+ Key ‘t’: tog the looping and non-looping playing mode (default looping).
+ Key ‘q’ or ‘Q’: exit the program

5. When key ‘t’ is pressed by the user at any time, the program should CONTINUE playing the audio from the current position. In other words, the program MUST NOT rewind to the beginning of the audio when the key is pressed.

6. There are Makefile in the folder when you want to compile and link your program.
$ make

* Useful References
SDL Reference manual.

* Appendix: Filter Coefficients for a 5th Order Low-pass Butterworth Filter

|  fc |    fs |     fc/fs | closest (fc/fs) in the table |
|-----+-------+-----------+------------------------------|
| 500 | 22050 | 0.0226757 |                       0.0225 |

| b= 4.92870054213945e-08 | 2.46435027106973e-07 | 4.92870054213945e-07 |
|    4.92870054213945e-07 | 2.46435027106973e-07 | 4.92870054213945e-08 |
|    a= -4.77126970811754 |     9.11101949606003 |    -8.70364051282520 |
|        4.15937748789777 |   -0.795485185830889 |                      |

|  fc |    fs |     fc/fs | closest (fc/fs) in the table |
|-----+-------+-----------+------------------------------|
| 200 | 22050 | 0.0090702 |                       0.0125 |
| 500 | 44100 | 0.0113378 |                       0.0125 |
| 200 | 44100 |  0.004535 |                       0.0125 |

| b= 2.74050909743195e-09 | 1.37025454871598e-08 | 2.74050909743195e-08 |
|    2.74050909743195e-08 | 1.37025454871598e-08 | 2.74050909743195e-09 |
|    a= -4.87292228923095 |     9.49972611051988 |    -9.26133224169541 |
|        4.51518275374949 |   -0.880654245646732 |                      |
